#!/usr/bin/env bash

jruby -S gem install logger -v '1.2.8'
jruby -S gem install fog -v '1.6.0'
jruby -S gem install chef -v '10.12.0'
jruby -S gem install net-ssh -v '2.2.2'
jruby -S gem install parallel -v '0.5.18'
jruby -S gem install rails -v '3.2.8'
jruby -S gem install sqlite3 -v '1.3.6'
jruby -S gem install jquery-rails -v '2.1.3'
jruby -S gem install coffee-rails -v '3.2.2'
jruby -S gem install sass-rails -v '3.2.5'
jruby -S gem install uglifier -v '1.3.0'
jruby -S gem install thin -v '1.4.1'
jruby -S gem install jmx4r -v '0.1.4'
